name: Rust
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./src
      run: cargo build --verbose
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Test
      working-directory: ./src
      run: cargo test --verbose
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
       profile: minimal
       toolchain: stable
       override: true

  bench:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    - name: Bench
      working-directory: ./benches
      run: cargo bench --verbose
    - name: Install and configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Set repository URL to use SSH
      run: |
        git remote set-url origin git@github.com:${{ github.repository }}.git
    - name: Push benchmark results to gh-pages
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r ./target/criterion/report/* .
        git add .
        git commit -m "Update benchmark results"
        git push -u origin gh-pages --force
